"""
This module provides classes and functions for analyzing scattering datasets collected at CHESS
(ID4B) with temperature dependence. It includes functions for loading temperature series and 
performing operations on all datasets in the series at once (e.g., cutting, fitting). 
"""
import os
import re
import warnings

import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
from nxs_analysis_tools import load_data, Scissors
from nxs_analysis_tools.fitting import LinecutModel
from nxs_analysis_tools.datareduction import load_transform, reciprocal_lattice_params
from lmfit.models import PseudoVoigtModel, LinearModel
from nexusformat.nexus import NXdata, NXfield, NXroot, NXentry, nxsave
def _normalize_temperature(t):
    """
    Normalize a temperature value to an int or float, accepting str, int, or float.
    Legacy 'p' notation (e.g. '15p5') is supported and converted to float (e.g. 15.5).
    Whole numbers are converted to int.
    """
    if isinstance(t, (int, float, np.number)):
        return int(t) if float(t).is_integer() else float(t)
    if isinstance(t, str):
        clean = t.replace('p', '.')
        try:
            val = float(clean)
            return int(val) if val.is_integer() else val
        except ValueError:
            return t
    return t


class TempDict(dict):
    """
    A dictionary for temperature-keyed data that transparently supports
    both numeric (int, float) and string representations of temperatures.
    """

    def _normalize_key(self, key):
        return _normalize_temperature(key)

    def __getitem__(self, key):
        norm_key = self._normalize_key(key)
        if super().__contains__(norm_key):
            return super().__getitem__(norm_key)
        if super().__contains__(key):
            return super().__getitem__(key)
        if super().__contains__(str(key)):
            return super().__getitem__(str(key))
        raise KeyError(key)

    def __setitem__(self, key, value):
        super().__setitem__(self._normalize_key(key), value)

    def __contains__(self, key):
        norm_key = self._normalize_key(key)
        return (
            super().__contains__(norm_key)
            or super().__contains__(key)
            or super().__contains__(str(key))
        )

    def get(self, key, default=None):
        try:
            return self[key]
        except KeyError:
            return default

    def pop(self, key, *args):
        norm_key = self._normalize_key(key)
        if super().__contains__(norm_key):
            return super().pop(norm_key, *args)
        if super().__contains__(key):
            return super().pop(key, *args)
        if super().__contains__(str(key)):
            return super().pop(str(key), *args)
        if args:
            return args[0]
        raise KeyError(key)


class TempDependence:
    """
    A class for analyzing temperature-dependent scattering datasets collected at CHESS (ID4B).

    The `TempDependence` class facilitates the loading, processing, and analysis of scattering
    data across different temperatures. It includes methods for handling datasets, setting
    lattice parameters, performing linecuts, modeling the data, and visualizing the results.

    Attributes
    ----------
    sample_directory : str
        Path to the directory containing the datasets.
    xlabel : str
        Label for the x-axis of plots, determined by the axis of the linecuts.
    datasets : dict
        Dictionary storing datasets keyed by temperature.
    temperatures : list of int or float
        List of temperatures for which data is available.
    scissors : dict
        Dictionary of Scissors objects, one for each temperature, used for data manipulation and
        linecut operations.
    linecuts : dict
        Dictionary storing the linecut data for each temperature.
    linecutmodels : dict
        Dictionary of LinecutModel objects, one for each temperature, used for fitting the linecuts.
    a, b, c, al, be, ga : float or None
        Lattice parameters (a, b, c, alpha, beta, gamma) of the crystal.
    a_star, b_star, c_star, al_star, be_star, ga_star : float or None
        Reciprocal lattice parameters (a*, b*, c*, alpha*, beta*, gamma*).
    xtec_data : :class:`nexusformat.nexus.tree.NXdata` or None
        Combined NXdata object generated by `to_xtec` for XTEC machine learning analysis.

    Methods
    -------
    set_temperatures(temperatures):
        Set the list of temperatures for the datasets.
    find_temperatures():
        Set the list of temperatures by automatically scanning the sample directory.
    set_sample_directory(path):
        Set the directory path where the datasets are located.
    initialize():
        Initialize Scissors and LinecutModel objects for each temperature.
    set_data(temperature, data):
        Set the dataset for a specific temperature.
    load_datasets(temperatures=None, exclude_temperatures=None, file_ending='hkli.nxs',
                  print_tree=True, use_nxlink=True):
        Load datasets from the sample directory, automatically detecting NXRefine or legacy CHESS format.
    to_xtec(filepath=None, temperatures=None, temp_axis_name='Te', temp_units='K', overwrite=True, entry_name='entry', data_name='data'):
        Export datasets as a combined NXdata object (and optional .nxs file) suitable for XTEC.
    get_sample_directory():
        Get the folder path where the datasets are located.
    clear_datasets():
        Clear the datasets stored in the TempDependence instance.
    set_Lattice_params(lattice_params):
        Set lattice parameters and calculate reciprocal lattice parameters.
    set_window(window, verbose=False):
        Set the extents of the integration window for each temperature.
    set_center(center):
        Set the central coordinate for the linecut for each temperature.
    cut_data(center=None, window=None, axis=None, verbose=False, normalize=False, empty_bins='both'):
        Perform data cutting for each temperature dataset.
    plot_linecuts(vertical_offset=0, **kwargs):
        Plot the linecuts obtained from data cutting.
    plot_linecuts_heatmap(ax=None, **kwargs):
        Plot a heatmap of the linecuts obtained from data cutting.
    plot_integration_window(temperature=None, show_highlight=True, width=None, height=None, **kwargs):
        Plot the integration window cross-sections for a specific temperature.
    set_model_components(model_components):
        Set the model components for all line cut models.
    set_param_hint(*args, **kwargs):
        Set parameter hints for all line cut models.
    make_params():
        Create parameters for all line cut models.
    guess():
        Make initial parameter guesses for all line cut models.
    print_initial_params():
        Print the initial parameter values for all line cut models.
    plot_initial_guess():
        Plot the initial guess for all line cut models.
    fit(verbose=False):
        Fit the line cut models for each temperature.
    plot_fit(mdheadings=False, **kwargs):
        Plot the fit results for each temperature.
    overlay_fits(numpoints=None, vertical_offset=0, cmap='viridis', ax=ax, 
                 data_kwargs=None, fit_kwargs=None):
        Plot raw data and fitted models for each temperature.
    fit_peak_simple():
        Perform a basic fit using a pseudo-Voigt peak shape, linear background, and no constraints.
    plot_order_parameter(ax, param_name='peakheight', **kwargs):
        Plot the temperature dependence of the peakheight parameter.
    print_fit_report():
        Print the fit report for each temperature.
    """

    def __init__(self, sample_directory=None):
        """
        Initialize the TempDependence class.

        Parameters
        ----------
        sample_directory : str, optional
            Path to the directory containing the temperature folders.
            If None, no directory is set initially.
        """

        if sample_directory is None:
            self.sample_directory = None
        else:
            self.set_sample_directory(sample_directory)

        self.xlabel = ''
        self.datasets = TempDict()
        self.temperatures = []
        self.scissors = TempDict()
        self.linecuts = TempDict()
        self.linecutmodels = TempDict()
        self.xtec_data = None
        self.a, self.b, self.c, self.al, self.be, self.ga, \
            self.a_star, self.b_star, self.c_star, self.al_star, self.be_star, self.ga_star \
            = [None] * 12

    def set_temperatures(self, temperatures):
        """
        Set the list of temperatures for the datasets.

        Parameters
        ----------
        temperatures : list
            List of temperatures to set.
        """
        self.temperatures = [_normalize_temperature(t) for t in temperatures]

    def _detect_format(self, file_ending='hkli.nxs'):
        """
        Detect whether sample_directory contains NXRefine transform files or legacy CHESS folders.

        Parameters
        ----------
        file_ending : str, optional
            File extension pattern for legacy CHESS datasets. Default is 'hkli.nxs'.

        Returns
        -------
        str or None
            'nxrefine', 'chess', or None if no valid data structure is found.
        """
        if self.sample_directory is None:
            raise ValueError("Sample directory is not set. Use set_sample_directory(path) first.")

        pattern = r'_(\d+(?:[p.]\d+)?)\.nxs'
        for item in os.listdir(self.sample_directory):
            item_path = os.path.join(self.sample_directory, item)
            if os.path.isfile(item_path) and re.search(pattern, item):
                return 'nxrefine'

        for item in os.listdir(self.sample_directory):
            item_path = os.path.join(self.sample_directory, item)
            if os.path.isdir(item_path):
                val = _normalize_temperature(item)
                if isinstance(val, (int, float)):
                    try:
                        if any(f.endswith(file_ending) or f.endswith('.nxs') for f in os.listdir(item_path)):
                            return 'chess'
                    except OSError:
                        pass
        return None

    def find_temperatures(self):
        """
        Set the list of temperatures by automatically scanning the sample directory for .nxs files.

        Supports both:
        - NXRefine transform files matching `*_<temperature>.nxs` directly in the sample directory.
        - Legacy CHESS file structure where subdirectories are named `<temperature>` and contain `.nxs` files.
        """

        # Assert that self.sample_directory must exist
        if self.sample_directory is None:
            raise ValueError("Sample directory is not set. Use set_sample_directory(path) first.")

        # Clear existing temperatures
        self.temperatures = []
        temps = []

        format_type = self._detect_format()
        if format_type == 'nxrefine':
            pattern = r'_(\d+(?:[p.]\d+)?)\.nxs'
            for item in os.listdir(self.sample_directory):
                item_path = os.path.join(self.sample_directory, item)
                if os.path.isfile(item_path):
                    match = re.search(pattern, item)
                    if match:
                        temps.append(_normalize_temperature(match.group(1)))
        elif format_type == 'chess':
            for item in os.listdir(self.sample_directory):
                item_path = os.path.join(self.sample_directory, item)
                if os.path.isdir(item_path):
                    val = _normalize_temperature(item)
                    if isinstance(val, (int, float)):
                        try:
                            if any(f.endswith('.nxs') for f in os.listdir(item_path)):
                                temps.append(val)
                        except OSError:
                            pass

        # Sort the temperatures numerically and deduplicate
        if temps:
            self.temperatures = sorted(list(dict.fromkeys(temps)), key=float)

    def set_sample_directory(self, path):
        """
        Set the directory path where the datasets are located.

        Parameters
        ----------
        path : str
            Path to the sample directory.
        """
        self.sample_directory = os.path.normpath(path)

    def initialize(self):
        """
        Initialize Scissors and LinecutModel objects for each temperature.
        """
        for temperature in self.temperatures:
            self.scissors[temperature] = Scissors()
            if temperature in self.datasets:
                self.scissors[temperature].set_data(self.datasets[temperature])
            self.linecutmodels[temperature] = LinecutModel()

    def set_data(self, temperature, data):
        """
        Set the dataset for a specific temperature.

        Parameters
        ----------
        temperature : int, float, or str
            Temperature for which to set the data.
        data : object
            The dataset to be set.
        """
        self.datasets[temperature] = data

    def load_datasets(
        self,
        temperatures=None,
        exclude_temperatures=None,
        file_ending='hkli.nxs',
        print_tree=True,
        use_nxlink=True,
        **kwargs,
    ):
        """
        Load datasets from the sample directory, automatically detecting the file structure format.

        Supports both:
        - NXRefine transform files matching `*_<temperature>.nxs` directly in `sample_directory`.
        - Legacy CHESS format with subdirectories named `<temperature>` containing `*<file_ending>` files.

        Parameters
        ----------
        temperatures : int, float, str, or list of int, float, or str, optional
            List of temperatures to load. If None, all available temperatures are loaded.
        exclude_temperatures : int, float, str, or list, optional
            Temperatures to skip. Applied after filtering with `temperatures`, if provided.
        file_ending : str, optional
            File extension pattern for legacy CHESS datasets. Default is 'hkli.nxs'.
        print_tree : bool, optional
            If True, prints the NeXus tree structure for each file. Default is True.
        use_nxlink : bool, optional
            If True (default), maintains the NXlink defined in NXRefine transform data files,
            referencing raw data in transform.nxs without eagerly loading 3D arrays into memory.
            Default is True.
        """
        # Backward compatibility for positional file_ending argument (e.g. load_datasets('hkli.nxs'))
        if isinstance(temperatures, str) and (temperatures.endswith('.nxs') or temperatures.endswith('.h5')):
            file_ending = temperatures
            temperatures = None

        if temperatures is not None:
            if not isinstance(temperatures, (list, tuple, set)):
                temperatures = [temperatures]
            temperatures = {_normalize_temperature(t) for t in temperatures}
        if exclude_temperatures is not None:
            if not isinstance(exclude_temperatures, (list, tuple, set)):
                exclude_temperatures = [exclude_temperatures]
            exclude_temperatures = {_normalize_temperature(t) for t in exclude_temperatures}

        format_type = self._detect_format(file_ending=file_ending)
        if format_type is None:
            raise FileNotFoundError(
                f"No valid NXRefine (*_<temperature>.nxs) or legacy CHESS (<temperature>/*{file_ending}) "
                f"datasets found in sample directory: '{self.sample_directory}'"
            )

        if format_type == 'nxrefine':
            pattern = r'_(\d+(?:[p.]\d+)?)\.nxs'
            filename_map = {}
            for item in os.listdir(self.sample_directory):
                match = re.search(pattern, item)
                if match:
                    filename_map[_normalize_temperature(match.group(1))] = item

            available_temps = sorted(list(filename_map.keys()), key=float)
            self.temperatures = [
                t for t in available_temps
                if (temperatures is None or t in temperatures)
                and (exclude_temperatures is None or t not in exclude_temperatures)
            ]

            for temperature in self.temperatures:
                item = filename_map[temperature]
                path = str(os.path.join(self.sample_directory, item))
                try:
                    self.datasets[temperature] = load_transform(path, print_tree=print_tree, use_nxlink=use_nxlink)
                except Exception as e:
                    print(f"Failed to load data for temperature {temperature} K from file {item}. Error: {e}")
                    raise

        elif format_type == 'chess':
            folder_map = {}
            for item in os.listdir(self.sample_directory):
                item_path = os.path.join(self.sample_directory, item)
                if os.path.isdir(item_path):
                    val = _normalize_temperature(item)
                    if isinstance(val, (int, float)):
                        try:
                            if any(f.endswith(file_ending) for f in os.listdir(item_path)):
                                folder_map[val] = item
                        except OSError:
                            pass

            available_temps = sorted(list(folder_map.keys()), key=float)
            self.temperatures = [
                t for t in available_temps
                if (temperatures is None or t in temperatures)
                and (exclude_temperatures is None or t not in exclude_temperatures)
            ]

            for T in self.temperatures:
                folder_name = folder_map.get(T, str(T))
                folder_path = os.path.join(self.sample_directory, folder_name)
                if not os.path.isdir(folder_path):
                    continue
                for file in os.listdir(folder_path):
                    if file.endswith(file_ending):
                        filepath = os.path.join(folder_path, file)
                        self.datasets[T] = load_data(filepath, print_tree)
                        break

        self.initialize()

    def get_sample_directory(self):
        """
        Get the folder path where the datasets are located.

        Returns
        -------
        str
            The folder path.
        """
        return self.sample_directory

    def clear_datasets(self):
        """
        Clear the datasets stored in the TempDependence instance.
        """
        self.datasets = TempDict()

    def to_xtec(
        self,
        filepath=None,
        temperatures=None,
        temp_axis_name='Te',
        temp_units='K',
        overwrite=True,
        entry_name='entry',
        data_name='data',
    ):
        """
        Export datasets as a combined NXdata object (and optional .nxs file) suitable for XTEC.

        This method compiles all or selected temperature datasets in `self.datasets`
        into a single multidimensional `NXdata` object with a leading 0-th axis representing
        the temperature (`Te` by default). The resulting structure matches the input format
        expected by XTEC-GPU machine learning tutorials.

        Parameters
        ----------
        filepath : str, Path, or bool, optional
            Path where the combined NeXus `.nxs` file should be written. If `True`,
            defaults to `'xtec_data.nxs'`. If `None` (default), no file is saved to disk.
        temperatures : list, optional
            List of temperatures to include in the export. If `None` (default), uses
            `self.temperatures` if set, otherwise all keys in `self.datasets` sorted
            numerically.
        temp_axis_name : str, optional
            Name of the temperature axis field. Default is `'Te'`.
        temp_units : str or None, optional
            Units attribute for the temperature axis field. Default is `'K'`.
        overwrite : bool, optional
            If `True` (default), overwrites existing file at `filepath`. If `False`
            and file exists, raises `FileExistsError`.
        entry_name : str, optional
            Name of the NXentry group when saving to file. Default is `'entry'`.
        data_name : str, optional
            Name of the NXdata group when saving to file. Default is `'data'`.

        Returns
        -------
        xtec_data : :class:`nexusformat.nexus.tree.NXdata`
            The combined NXdata object with the temperature axis at the 0-th position.

        Raises
        ------
        ValueError
            If `self.datasets` is empty, no valid temperatures are found, or dataset
            shapes / signals are inconsistent.
        KeyError
            If a requested temperature in `temperatures` cannot be resolved in `self.datasets`.
        FileExistsError
            If `filepath` already exists and `overwrite` is `False`.
        """
        if not self.datasets:
            raise ValueError("No datasets found in TempDependence instance. Please load or add datasets first.")

        if temperatures is None:
            if self.temperatures:
                selected_temps = list(self.temperatures)
            else:
                selected_temps = sorted(self.datasets.keys(), key=lambda t: float(str(t).replace('p', '.')))
        else:
            selected_temps = list(temperatures)

        if not selected_temps:
            raise ValueError("No temperatures specified or found to export.")

        def _resolve_temp_key(t, datasets):
            if t in datasets:
                return t
            str_t = str(t)
            if str_t in datasets:
                return str_t
            p_format = str_t.replace('.', 'p')
            if p_format in datasets:
                return p_format
            try:
                t_val = float(str_t.replace('p', '.'))
                for k in datasets:
                    try:
                        if np.isclose(float(str(k).replace('p', '.')), t_val):
                            return k
                    except (ValueError, TypeError):
                        continue
            except (ValueError, TypeError):
                pass
            raise KeyError(f"Temperature '{t}' not found in datasets. Available temperatures: {list(datasets.keys())}")

        resolved_keys = [_resolve_temp_key(t, self.datasets) for t in selected_temps]

        # Extract numeric temperature values (int if all are integers, float otherwise)
        temp_floats = []
        for k in resolved_keys:
            try:
                temp_floats.append(float(str(k).replace('p', '.')))
            except ValueError:
                raise ValueError(
                    f"Could not parse temperature '{k}' as a numeric value. "
                    "Temperatures must be convertible to floats or ints."
                )

        if all(v.is_integer() for v in temp_floats):
            temp_array = np.array(temp_floats, dtype=int)
        else:
            temp_array = np.array(temp_floats, dtype=float)

        first_key = resolved_keys[0]
        first_dataset = self.datasets[first_key]
        if not hasattr(first_dataset, 'nxsignal') or first_dataset.nxsignal is None:
            raise ValueError(f"Dataset for temperature '{first_key}' has no nxsignal.")
        if not hasattr(first_dataset, 'nxaxes') or first_dataset.nxaxes is None:
            raise ValueError(f"Dataset for temperature '{first_key}' has no nxaxes.")

        expected_shape = first_dataset.nxsignal.shape
        for key in resolved_keys:
            d = self.datasets[key]
            if not hasattr(d, 'nxsignal') or d.nxsignal is None:
                raise ValueError(f"Dataset for temperature '{key}' has no nxsignal.")
            if d.nxsignal.shape != expected_shape:
                raise ValueError(
                    f"Dataset for temperature '{key}' has shape {d.nxsignal.shape}, "
                    f"which does not match expected shape {expected_shape}."
                )

        # Stack signals across temperatures along axis 0
        signal_list = [np.asarray(self.datasets[k].nxsignal.nxdata) for k in resolved_keys]
        stacked_signal = np.stack(signal_list, axis=0)

        # Copy attributes from first signal
        signal_attrs = {}
        if hasattr(first_dataset.nxsignal, 'attrs'):
            signal_attrs = {
                attr: val.nxdata if hasattr(val, 'nxdata') else val
                for attr, val in first_dataset.nxsignal.attrs.items()
            }
        signal_name = first_dataset.nxsignal.nxname or 'counts'
        signal_field = NXfield(stacked_signal, name=signal_name, attrs=signal_attrs)

        # Build temperature axis field
        temp_attrs = {'units': temp_units} if temp_units else {}
        temp_field = NXfield(temp_array, name=temp_axis_name, attrs=temp_attrs)

        # Build spatial axes fields
        spatial_axes = []
        for ax in first_dataset.nxaxes:
            ax_attrs = {}
            if hasattr(ax, 'attrs'):
                ax_attrs = {
                    attr: val.nxdata if hasattr(val, 'nxdata') else val
                    for attr, val in ax.attrs.items()
                }
            spatial_axes.append(NXfield(np.asarray(ax.nxdata), name=ax.nxname, attrs=ax_attrs))

        all_axes = tuple([temp_field] + spatial_axes)
        xtec_data = NXdata(signal_field, all_axes)

        self.xtec_data = xtec_data

        if filepath is not None:
            if isinstance(filepath, bool):
                if filepath:
                    filepath = 'xtec_data.nxs'
                else:
                    return xtec_data

            filepath = str(filepath)
            if os.path.exists(filepath) and not overwrite:
                raise FileExistsError(f"File '{filepath}' already exists and overwrite=False.")

            dirname = os.path.dirname(os.path.abspath(filepath))
            if dirname and not os.path.exists(dirname):
                os.makedirs(dirname, exist_ok=True)

            root = NXroot()
            root[entry_name] = NXentry()
            root[entry_name][data_name] = xtec_data
            nxsave(filepath, root)

        return xtec_data


    def set_lattice_params(self, lattice_params):
        """
        Set lattice parameters and calculate reciprocal lattice parameters.

        Parameters
        ----------
        lattice_params : tuple
            Tuple containing lattice parameters (a, b, c, al, be, ga).
        """
        self.a, self.b, self.c, self.al, self.be, self.ga = lattice_params
        self.a_star, self.b_star, self.c_star, \
            self.al_star, self.be_star, self.ga_star = reciprocal_lattice_params(lattice_params)

    def set_window(self, window, verbose=False):
        """
        Set the extents of the integration window for each temperature.

        Parameters
        ----------
        window : tuple
            Extents of the window for integration along each axis.
        verbose : bool, optional
            Enables printout of linecut axis and integrated axes. Default is False.
        """
        for T in self.temperatures:
            if verbose:
                print("----------------------------------")
                print(f"T = {T} K")
            self.scissors[T].set_window(window, verbose)

    def set_center(self, center):
        """
        Set the central coordinate for the linecut for each temperature.

        Parameters
        ----------
        center : tuple
            Central coordinate around which to perform the linecut.
        """
        for T in self.temperatures:
            self.scissors[T].set_center(center)

    def cut_data(self, center=None, window=None, axis=None, verbose=False,
                 normalize=False, empty_bins='both'):
        """
        Perform data cutting for each temperature dataset.

        Parameters
        ----------
        center : tuple, optional
            The center point for cutting the data.
            Defaults to the first temperature's center if None.
        window : tuple, optional
            The window size for cutting the data.
            Defaults to the first temperature's window if None.
        axis : int or None, optional
            The axis along which to perform the cutting.
            Defaults to the longest axis in `window` if None.
        verbose : bool, optional
            Enables printout of linecut progress. Default is False.
        normalize : bool, optional
            Whether to normalize the linecut by the number of non-empty bins along the
            integrated directions. Default False.
        empty_bins : {'both', 'nan', 'none'}, optional
            Defines which bins are considered empty when counting valid bins for normalization:
            - 'both': Ignore NaNs and zeros. (Default)
            - 'nan': Ignore only NaNs.
            - 'none': Count all voxels within the integration window.

        Returns
        -------
        dict
            A dictionary of linecuts obtained from the cutting operation.
        """

        for T in self.temperatures:
            if verbose:
                print("-------------------------------")
                print(f"Cutting T = {T} K data...")
            self.scissors[T].set_center(center)
            self.scissors[T].set_window(window)
            self.scissors[T].cut_data(axis=axis, verbose=verbose,
                                      normalize=normalize, empty_bins=empty_bins)
            self.linecuts[T] = self.scissors[T].linecut
            self.linecutmodels[T].set_data(self.linecuts[T])

        xlabel_components = [self.linecuts[self.temperatures[0]].nxaxes[0].nxname
                             if i == self.scissors[self.temperatures[0]].axis
                             else str(c) for i, c in
                             enumerate(self.scissors[self.temperatures[0]].center)
                            ]
        self.xlabel = ' '.join(xlabel_components)

        return self.linecuts

    def plot_linecuts(self, ax=None, vertical_offset=0, **kwargs):
        """
        Plot the linecuts obtained from data cutting.

        Parameters
        ----------
        ax : :class:`matplotlib.axes.Axes`, optional
            The matplotlib Axes object on which to plot. If None, a new figure 
            and axes are created. Default None.
        vertical_offset : float, optional
            The vertical offset between linecuts on the plot. The default is 0.
        **kwargs
            Additional keyword arguments passed to the matplotlib plot function.
        """
        if ax is None:
            fig, ax = plt.subplots()

        # Get the Viridis colormap
        cmap = mpl.colormaps.get_cmap('viridis')

        # Reverse zorder
        zorder = 0

        for i, linecut in enumerate(self.linecuts.values()):
            
            x_data = linecut.nxaxes[0].nxdata
            y_data = linecut.nxsignal.nxdata + i * vertical_offset
            p = ax.plot(x_data, y_data, color=cmap(i / len(self.linecuts)), label=self.temperatures[i], 
                    zorder=zorder, **kwargs)
            zorder -= 1

        ax.set(xlabel=self.xlabel,
               ylabel=self.linecuts[self.temperatures[0]].nxsignal.nxname)

        # Get the current legend handles and labels
        handles, labels = plt.gca().get_legend_handles_labels()

        # Reverse the order of handles and labels
        handles = handles[::-1]
        labels = labels[::-1]

        # Create a new legend with reversed order
        plt.legend(handles, labels)

    def plot_linecuts_heatmap(self, ax=None, **kwargs):
        """
        Plot the linecuts obtained from data cutting.

        Parameters
        ----------
        ax : :class:`matplotlib.axes.Axes`, optional
            The axes on which to plot the heatmap. If None, a new figure and axes
            are created. The default is None.
        **kwargs
            Additional keyword arguments to be passed to the `pcolormesh` function.

        Returns
        -------
        QuadMesh
            The plotted heatmap object.
        """

        # Retrieve linecut data for the first temperature and extract x-axis data
        cut = self.linecuts[self.temperatures[0]]
        x = cut.nxaxes[0].nxdata

        # Convert the list of temperatures to a NumPy array for the y-axis
        y = np.array([float(str(t).replace('p', '.')) for t in self.temperatures])

        # Collect counts from each temperature and ensure they are numpy arrays
        v = [self.linecuts[T].nxsignal.nxdata for T in self.temperatures]

        # Convert list of arrays to a 2D array for the heatmap
        v_2d = np.array(v)

        # Create the grid for the heatmap
        X, Y = np.meshgrid(x, y)

        # Plot using pcolormesh
        if ax is None:
            _, ax = plt.subplots()
        p = ax.pcolormesh(X, Y, v_2d, **kwargs)
        plt.colorbar(p, label='counts')
        ax.set(xlabel=self.xlabel, ylabel=r'$T$ (K)')

        return p

    def plot_integration_window(self, temperature=None, show_highlight=True, width=None, height=None,
                                label=None, highlight_color='red', **kwargs):
        """
        Plots the principal cross-sections of the dataset for a specific temperature.

        Parameters
        ----------
        temperature : str, optional
            The temperature at which to plot. If provided, the plot will be 
            generated using the dataset corresponding to the specified temperature. 
            If not provided, defaults to the first temperature.
        show_highlight : bool, optional
            Whether to overlay a rectangle highlighting the integration window. Default is True.
        width : float, optional
            Width of the visible x-axis range to zoom in on the integration region.
        height : float, optional
            Height of the visible y-axis range to zoom in on the integration region.
        label : str, optional
            Label for the rectangle patch used in the legend.
        highlight_color : str, optional
            Color of the rectangle edges highlighting the integration window. Default is 'red'.
        **kwargs : keyword arguments, optional
            Additional keyword arguments passed to customize the plot.

        Returns
        -------
        plots : tuple of :class:`matplotlib.collections.QuadMesh`
            The plotted QuadMesh objects.
        """
        # Default to the first temperature if none is provided
        if temperature is None:
            target_temp = self.temperatures[0]
            warnings.warn(
                f"No temperature specified. Defaulting to temperature {target_temp} K. "
                "To specify a temperature, use the `temperature` argument.",
                UserWarning,
                stacklevel=2
            )
        else:
            target_temp = temperature
        
        # Fetch the appropriate dataset
        target_data = self.datasets[target_temp]
        
        # Route to the scissor's unified plotting method
        p = self.scissors[target_temp].plot_integration_window(
            data=target_data,
            show_highlight=show_highlight,
            width=width,
            height=height,
            label=label,
            highlight_color=highlight_color,
            **kwargs
        )
        
        return p

    def set_model_components(self, model_components):
        """
        Set the model components for all line cut models.

        This method sets the same model components for all line cut models in the
        analysis. It iterates over each line cut model and calls their respective
        `set_model_components` method with the provided `model_components`.

        Parameters
        ----------
        model_components : Model, CompositeModel, or iterable of Model
            The model components to set for all line cut models.

        """
        [linecutmodel.set_model_components(model_components) for
         linecutmodel in self.linecutmodels.values()]

    def set_param_hint(self, *args, **kwargs):
        """
        Set parameter hints for all line cut models.

        This method sets the parameter hints for all line cut models in the analysis.
        It iterates over each line cut model and calls their respective `set_param_hint` method
        with the provided arguments and keyword arguments. These are implemented when the
        .make_params() method is called.

        Parameters
        ----------
        *args
            Variable length argument list.
        **kwargs
            Arbitrary keyword arguments.

        """
        [linecutmodel.set_param_hint(*args, **kwargs)
         for linecutmodel in self.linecutmodels.values()]
    
    def params_set(self, name, **kwargs):
        """
        Set constraints on a parameter for all line cut models.

        This method updates the specified parameter across all models in
        `self.linecutmodels` using the keyword arguments provided. These
        keyword arguments are passed to the `set()` method of the parameter,
        which comes from a `lmfit.Parameters` object.

        Parameters
        ----------
        name : str
            Name of the parameter to modify (must exist in each model).
        **kwargs
            Constraint arguments passed to `Parameter.set()`, such as `value`,
            `min`, `max`, `vary`, etc.

        Raises
        ------
        KeyError
            If the parameter `name` does not exist in one of the models.

        Example
        -------
        >>> sample.params_set('peakamplitude', value=5, min=0, vary=True)
        """

        for linecutmodel in self.linecutmodels.values():
            linecutmodel.params[name].set(**kwargs)

    def make_params(self):
        """
        Create and initialize the parameters for all models.

        This method creates the parameters for all line cut models in the analysis.
        It iterates over each line cut model and calls their respective `make_params` method.
        """
        [linecutmodel.make_params() for linecutmodel in self.linecutmodels.values()]

    def guess(self):
        """
        Make initial parameter guesses for all line cut models. This overwrites any prior initial
        values and constraints.

        This method generates initial parameter guesses for all line cut models in the analysis.
        It iterates over each line cut model and calls their respective `guess` method.

        """
        [linecutmodel.guess() for linecutmodel in self.linecutmodels.values()]

    def print_initial_params(self):
        """
        Print the initial parameter values for all line cut models.

        This method prints the initial parameter values for all line cut models
        in the analysis. It iterates over each line cut model and calls their
        respective `print_initial_params` method.

        """
        [linecutmodel.print_initial_params() for linecutmodel in self.linecutmodels.values()]

    def plot_initial_guess(self):
        """
        Plot the initial guess for all line cut models.

        This method plots the initial guess for all line cut models in the analysis.
        It iterates over each line cut model and calls their respective `plot_initial_guess` method.

        """
        for T, linecutmodel in self.linecutmodels.items():
            _, ax = plt.subplots()
            ax.set(title=f"{T} K")
            linecutmodel.plot_initial_guess()

    def fit(self, verbose=False):
        """
        Fit the line cut models.

        This method fits the line cut models for each temperature in the analysis.
        It iterates over each line cut model, performs the fit, and prints the fitting progress.

        Parameters
        ----------
       verbose : bool, optional
            Enables printout of fitting progress. Default False.

        """
        for T, linecutmodel in self.linecutmodels.items():
            if verbose:
                print(f"Fitting {T} K  data...")
            linecutmodel.fit()
            if verbose:
                print("Done.")
        print("Fits completed.")

    def plot_fit(self, mdheadings=False, **kwargs):
        """
        Plot the fit results.

        This method plots the fit results for each temperature in the analysis.
        It iterates over each line cut model, calls their respective `plot_fit` method,
        and sets the xlabel, ylabel, and title for the plot.

        """
        for T, linecutmodel in self.linecutmodels.items():
            # Create a markdown heading for the plot
            if mdheadings:
                display(Markdown(f"### {T} K Fit Results"))
            # Plot fit
            linecutmodel.plot_fit(xlabel=self.xlabel,
                                  ylabel=self.datasets[self.temperatures[0]].nxsignal.nxname,
                                  title=f"{T} K",
                                  **kwargs)

    def overlay_fits(self, numpoints=None, vertical_offset=0, cmap='viridis', ax=None,
                     data_kwargs=None, fit_kwargs=None):
        """
        Plot raw data and fitted models for each temperature with optional vertical offsets.

        Parameters:
        -----------
        numpoints : int or None, default=None
            Number of points to evaluate for the fitted model curves.
            If None, uses the number of raw data points for each linecut.
        vertical_offset : float, default=0
            Amount to vertically offset each linecut for clarity.
        cmap : str, default='viridis'
            Name of the matplotlib colormap used to distinguish different temperatures.
        ax : :class:`matplotlib.axes.Axes` or None, default=None
            Axis object to plot on. If None, a new figure and axis are created.
        data_kwargs : dict
            Keyword arguments to be passed to the data plot function.
        fit_kwargs : dict
            Keyword arguments to be passed to the fit plot function.


        The function:
        - Uses a colormap to assign unique colors to each temperature.
        - Plots raw data alongside evaluated fit models for each linecut.
        - Vertically offsets each trace by a constant value for visual separation.
        - Displays a legend in reverse order to match top-to-bottom visual stacking.
        - Automatically labels the x- and y-axes based on NeXus-style data metadata.
        """

        # Create a figure and axes if an axis is not already provided
        _, ax = plt.subplots() if ax is None else (None, ax)

        if data_kwargs is None:
            data_kwargs = {}
        if fit_kwargs is None:
            fit_kwargs = {}

        # Generate a color palette for the various temperatures
        cmap = plt.get_cmap(cmap)
        colors = [cmap(i / len(self.temperatures)) for i, _ in enumerate(self.temperatures)]

        for i, lm in enumerate(self.linecutmodels.values()):
            # Plot the raw data
            ax.plot(lm.x, lm.y + vertical_offset * i, '.', c=colors[i], **data_kwargs)

            # Evaluate the fit
            numpoints = len(lm.x) if numpoints is None else numpoints
            x_eval = np.linspace(lm.x.min(), lm.x.max(), numpoints)
            y_eval = lm.modelresult.eval(x=x_eval)
            ax.plot(x_eval, y_eval + vertical_offset * i, '-', c=colors[i], label=self.temperatures[i], **fit_kwargs)

        # Reverse legend entries to match top-to-bottom stacking
        handles, labels = ax.get_legend_handles_labels()
        ax.legend(handles[::-1], labels[::-1])

        # Add axis labels
        ax.set(xlabel=lm.data.nxaxes[0].nxname, ylabel=lm.data.nxsignal.nxname)
        
    def fit_peak_simple(self):
        """
        Fit all linecuts in the temperature series using a pseudo-Voigt peak shape and linear
        background, with no constraints.
        """

        for T in self.temperatures:
            linecutmodel = self.linecutmodels[T]
            linecutmodel.set_model_components([PseudoVoigtModel(prefix='peak'),
                                                LinearModel(prefix='background')])
            linecutmodel.make_params()
            linecutmodel.guess()
            linecutmodel.params['peakamplitude'].set(min=0)
            linecutmodel.fit()

    def plot_order_parameter(self, param_name='peakheight', ax=None, **kwargs):
        """
        Plot the temperature dependence of the peak height (order parameter).

        This method extracts the values of a chosen parameter from each temperature-dependent
        line cut fit stored in `linecutmodels` and plots it as a function of temperature.

        Parameters
        ----------
        ax : :class:`matplotlib.axes.Axes`, optional
            Axis object to plot on. If None, a new figure and axis are created.
        param_name : str, optional
            The name of the lmfit parameter to extract. Default is 'peakheight'.
        **kwargs
            Keyword arguments to be passed to the plot function.


        Returns
        -------
        Figure
            Matplotlib Figure object containing the peak height vs. temperature plot.
        Axes
            Matplotlib Axes object associated with the figure.

        Notes
        -----
        - Temperature values are converted to floats for plotting.
        - Peak heights are extracted from the 'peakheight' parameter in the model results.
        - The plot uses standard axes labels with temperature in Kelvin.
        """

        # Create an array of temperature values
        temperatures = [float(str(T).replace('p', '.')) for T in self.temperatures]

        # Create an empty list for the peak heights
        peakheights = []

        # Extract the peakheight at every temperature
        for T in self.temperatures:
            
            # Verify that the fit has already been completed
            if self.linecutmodels[T].modelresult is None:
                raise AttributeError("Model result is empty. Have you fit the data to a model?")
            
            peakheights.append(self.linecutmodels[T].modelresult.params[param_name].value)

        # Plot the peakheights vs. temperature
        if ax is None:
            fig, ax = plt.subplots()
        else:
            fig = ax.figure
        ax.plot(temperatures, peakheights, **kwargs)
        ax.set(xlabel='$T$ (K)', ylabel=param_name)
        return fig, ax

    def print_fit_report(self):
        """
        Plot the fit results.

        This method plots the fit results for each temperature in the analysis.
        It iterates over each line cut model, calls their respective `plot_fit` method,
        and sets the xlabel, ylabel, and title for the plot.

        """
        for T, linecutmodel in self.linecutmodels.items():
            print(f"[[[{T} K Fit Report]]]")
            linecutmodel.print_fit_report()
